// sprites.js — 16x16 pixel-art sprites drawn as ASCII grids.
//
// Data half (PALETTE, SPRITES, DEFAULT_TINTS, renderToRGBA) is pure and imports in Node.
// DOM half (spriteCanvas, spriteURL) touches `document` lazily, only when called.
//
// Sprite keys used by the app (all must exist):
//   Plants:  seedling lettuce leafy kale chard cabbage broccoli bokchoy bean pea carrot beet
//            radish turnip onion leek garlic potato tomato pepper eggplant melon watermelon
//            squash zucchini cucumber pumpkin corn strawberry blueberry raspberry herb basil
//            parsley dill rosemary flower dahlia marigold nasturtium sunflower lupine bulb
//            euphorbia tree fig groundcherry tomatillo shrub unknown
//   Icons:   icon_yard icon_bed icon_calendar icon_book icon_basket icon_seed icon_can
//            icon_frost icon_sun icon_shovel icon_gear icon_plus icon_trash icon_lock
//            icon_unlock icon_user icon_cloud icon_cloud_off icon_sprout icon_map icon_check
//            icon_close icon_edit icon_warn icon_heart icon_clash
//   Tiles:   tile_grass tile_grass2 tile_soil tile_soil2 tile_path tile_wood tile_water
//
// Tint slots (uppercase): A = accent, Q = accent shadow (auto-derived from A),
//                         B = accent 2, V = accent-2 shadow (auto-derived from B).
// Pass tint as { A: '#rrggbb', B: '#rrggbb' } (Q / V may also be given explicitly).

export const PALETTE = Object.freeze({
  '.': 'transparent',
  k: '#1a1c2c', // ink (outlines)
  s: '#94b0c2', // silver
  w: '#f4f4f4', // white
  h: '#566c86', // gray
  p: '#5d275d', // plum
  r: '#b13e53', // red
  o: '#ef7d57', // orange
  y: '#ffcd75', // yellow
  l: '#a7f070', // lime
  g: '#38b764', // green
  d: '#1e6b45', // dark green
  t: '#257179', // teal
  n: '#29366f', // navy
  b: '#3b5dc9', // blue
  c: '#41a6f6', // sky
  u: '#8b5cb8', // purple
  i: '#f5a3c7', // pink
  m: '#b07a4a', // wood
  x: '#734c3b', // brown
  e: '#4a2f25', // soil dark
  f: '#f2e6c9', // cream
});

export const TINT_SLOTS = Object.freeze(['A', 'Q', 'B', 'V']);

// Default accent colours for every sprite that uses tint slots.
export const DEFAULT_TINTS = Object.freeze({
  lettuce:   { A: '#38b764' },
  chard:     { A: '#b13e53' },
  carrot:    { A: '#ef7d57' },
  beet:      { A: '#b13e53' },
  radish:    { A: '#b13e53' },
  tomato:    { A: '#b13e53' },
  pepper:    { A: '#ef7d57' },
  eggplant:  { A: '#5d275d' },
  melon:     { A: '#ffcd75' },
  squash:    { A: '#ffcd75' },
  flower:    { A: '#f5a3c7', B: '#ffcd75' },
  dahlia:    { A: '#b13e53' },
  lupine:    { A: '#8b5cb8' },
  bulb:      { A: '#ffcd75' },
  euphorbia: { A: '#a7f070' },
  tree:      { A: '#b13e53' },
});

const FALLBACK_TINT = { A: '#b13e53', B: '#ffcd75' };
const INK = [0x1a, 0x1c, 0x2c];
const SHADE_AMOUNT = 0.35; // lerp toward ink => ~30% darker, slightly cool

/* ------------------------------------------------------------------ art -- */

const ART = {
// ================================================================ plants ==
seedling: `
................
................
................
................
................
................
..kkkk....kkkk..
.kllllk..kllggk.
kllllggkkgglgddk
kllggggkkggggddk
.kgggggkkgggddk.
..kkggdkkgddkk..
....kkkgdkkk....
......kgdk......
.....kkgdkk.....
...eexxmxxxee...
`,
lettuce: `
................
................
................
................
................
.....kk..kk.....
....kAAkkAAk....
...kAllAAllAk...
..kAAlllllllAk..
.kAAllAlllAllAk.
kAAAlAAllAAlAAQk
kQAAAAAlAAAAAQQk
kQQAAAQAAQAAQQQk
.kQQQQQQQQQQQQk.
..kkkkkkkkkkkk..
...eexxmxxxee...
`,
leafy: `
................
................
................
................
................
.......kkk......
......kglgk.....
.kkk..kglgk.kkk.
kgllk.kgggk.kgdk
kggldkkgdgkkdgdk
.kggdkkgdgkkddk.
..kgddkgdgkddk..
...kgddgdgddk...
....kkddddkk....
......kkkk......
....eexxmxee....
`,
kale: `
......k.kk......
.....kgkgtk.....
..kk.kggtttk.kk.
.kgtkkgtgtdkktdk
kgtgtkgtgtdktgtk
kgttgkgtgtdkgtdk
.kgttgkggtkgtddk
.kgtttgkgtkgtddk
..kgttgkgkgtddk.
..kgtttgggtddk..
...kkttggltdkk..
.....kkllldk....
......kllk......
......kllk......
.....kkldkk.....
...eexxmxxxee...
`,
chard: `
................
...kkk....kkk...
..kgllk..kgggk..
.kglgggkkggdddk.
.kgggAgkkgAgddk.
.kggAggkkgAgddk.
.kgAgggkkgAddkk.
..kAgdk.kkAddk..
..kAdk...kAdk...
...kAk...kAk....
...kAk..kAk.....
....kAk.kAk.....
.....kAkAk......
.....kAAQk......
.....kAAQk......
...eexxmxxxee...
`,
cabbage: `
................
................
................
................
................
......kkkk......
....kkllllkk....
...klllllllgk...
..kllwlllllggk..
.kkllllllllggkk.
ktkglllllgggktck
kttkgglgggggkttk
kcttkggggggkttdk
.ktttkkkkkktttk.
..kkttttttttkk..
...eexxmxxxee...
`,
broccoli: `
................
.....kk.kkk.....
....kglkgllkk...
...kgllgglgggk..
..kgglggdgglgdk.
..kglgddggddgdk.
..kgdgggdddgddk.
...kddkdddkddk..
....kkklgkkkk...
.kk...klgk...kk.
kdgk..klgk..kgdk
kdggk.klgk.kggdk
.kdggkklgkkggdk.
..kkdgklgkgdkk..
....kkklgkkk....
...eexxmxxxee...
`,
bokchoy: `
......kkkk......
.kkk.kglggk.kkk.
kgllkkgllgdkkgdk
kglggkglggdkggdk
kgggdkgggddkgddk
kggddkggdddkgddk
.kgdkkgwgddkkdk.
.kgwdkkwwdkkwdk.
..kwkkwwfwkkwk..
..kwwkwwfskkwk..
...kwwwffsswk...
...kwwwffsssk...
...kwwffssssk...
....kwffsssk....
.....kkkkkk.....
...eexxmxxxee...
`,
bean: `
......kkk.......
.....kglgk......
..kkkgllggkkk...
.kgllkgggkgllk..
kgllggkgkglggdk.
kglgggdkkgggddk.
.kggdddkkgdddk..
..kkkkkgdkkkkk..
..kllk.kgk.kk...
.kllgk.kgkkllk..
.klgk..kgkklgk..
.klgk..kgk.klgk.
..klgk.kgk.klgk.
..klgk.kgk..kgk.
...kk.kkgdk..k..
...eexxmxxxee...
`,
pea: `
kkk..........kkk
kmk....kk....kmk
kmk...kglk...kmk
kmffffkgkfffffmk
kmkkkk.kgk.kkkmk
kmkgllkkgkkglkmk
kmkggdkkgkkgdkmk
kmfkkkfkgkfkkfmk
kmk.klkkgkkkkkmk
kmk.klkkgkwiwkmk
kmk.klkkgkkwkkmk
kmffkkkkgkffffmk
kmk...kgdk.klkmk
kmk...kgdk.klkmk
kmk..kkgdkk.kkmk
kxkeexxmxxxeekxk
`,
carrot: `
................
..k.k...k.k.k...
.kgkgk.kgkglkgk.
..kgdk.kdkgkgk..
.kgkgkkglkdgk...
..kgkdkdkgkdk...
...kkgdgdgkk....
.....kgdgdk.....
.....kkdgkk.....
....kAAAAAQk....
....kAwAAAQk....
....kAAAAQQk....
.....kAAAQk.....
...eekAAQkee....
..eexxkAQkxxe...
..eexxxkkxxxee..
`,
beet: `
................
..kkk.....kkk...
.kgglk...kgddk..
.kglAgk.kgAgdk..
.kggAgk.kgAddk..
..kgAgkkkgAdk...
...kkAkAkAkk....
.....kAkAk......
......kAAk......
....kkAAAAkk....
...kAwAAAAAQk...
...kAAAAAAQQk...
...kAAAAAQQQk...
..eekQAAQQQkee..
.eexxxkQQkkxxee.
..eexxxkQkxxee..
`,
radish: `
................
................
................
....kk....kk....
...kllk..kglk...
..kllgk..kggdk..
..klggdkkgggdk..
...kgddkkdgdk...
....kkdggdkk....
......kgdk......
.....kkAAkk.....
....kAwAAAQk....
....kAAAAAQk....
...eekAAAQkee...
..eexxkwwkxxee..
...eexxkwkxee...
`,
turnip: `
................
...kk......kk...
..kglk....kgdk..
..kgldk..kggdk..
..kggdk..kgddk..
...kgdkkkkgdk...
....kkgdgdkk....
......kgdk......
.....kkkkkk.....
....kuiuuupk....
...kuuuuuuppk...
...kwwwwwwwsk...
...kwwffwwssk...
...eekwwwsskee..
..eexxkkwskxxee.
...eexxxkkxxee..
`,
onion: `
......k....k....
.....kgk..kgk...
..k..kgk..kdk...
.kgk.kgk.kgdk...
.kgdkkgk.kgk....
..kgdkgdkkgk....
...kgdgdkgdk....
....kgdgdgk.....
.....kgddk......
.....kyyok......
....kyyyyok.....
...kywyyyook....
...kyyyyyoomk...
...ekyyyoomkee..
..eexkkommkkxee.
...eexxkkkxxee..
`,
leek: `
.kk..........kk.
ktgk........ktdk
.ktgk..kk..ktdk.
..ktgkkgtkktdk..
...ktgkgtkgdk...
....ktgktgdk....
.....ktgtdk.....
.....klgtdk.....
.....kllgdk.....
.....kwlgsk.....
.....kwwfsk.....
.....kwwfsk.....
.....kwwfsk.....
...eekwwfskee...
..eexxkwfskxxee.
...eexxkkkxxee..
`,
garlic: `
.........kkk....
........kglgk...
....kk..kgkkgk..
...kgdk..kgkgk..
...kgdk...kgdk..
....kgdk..kgk.kk
.....kgdk.kgkkdk
......kgdkgdkgdk
......kgdkgdgdk.
.......kgdgddk..
......kkkkkkk...
.....kwwfwfsk...
....kwwwfwfssk..
...eekwwfwfsskee
..eexxkkssskkxxe
...eexxxkkkxxee.
`,
potato: `
................
.....kkk.kkk....
....kwywkwywk...
...kkkwkkkwkkk..
..kgllkgkkglgk..
.kglggkgkgggddk.
.kgggdkgkkgdddk.
kgllgdkgkglggdk.
kgggddkgkgggddk.
.kkddkkgkkddkk..
..eeekkgdkkeee..
exkkkkkxxexxxxxe
ekymmmmkxxkkkkxe
ekmymmxkxkymmmkx
ekmmmxxkekmmmxke
eekkkkkeeekkkkee
`,
tomato: `
......kkkk......
....kkglllkk....
...kgllgggddk...
..kglggdgdddgk..
..kggdkkgkkddk..
..kkkkkgk..kkkk.
......kgkkkAgdAk
.kkkk.kgk.kwAAAk
kAgdAkkgk.kAAAQk
kwAAAkkgk.kQAQQk
kAAAQkkgk..kkkk.
kQAQQkkgkkgddk..
.kkkk.kgkgdk....
......kgkk......
.....kkgdkk.....
...eexxmxxxee...
`,
pepper: `
....kkk..kkk....
...kgllkkglgk...
..kglggdkgggdk..
.kglgggdkggddgk.
.kggdddkgdddgdk.
..kkkkkgkkkkkk..
..kgk.kgk..kgk..
.kgddkkgk..kgk..
.kwAAkkgk.kgddk.
.kAAQkkgk.kwAAk.
.kAAQkkgk.kAAQk.
.kAQQkkgk.kAAQk.
..kQk.kgk.kAQQk.
...k..kgk..kQk..
.....kkgdkk.k...
...eexxmxxxee...
`,
eggplant: `
...kkkk..kkkk...
..kglllkkgllgk..
.kglgggdkggggdk.
.kgggddkkgggddk.
..kkkggkkgddkk..
..kggk.kgk......
.kgddgkkgk.kggk.
..kwAk.kgkkgddgk
.kwAAAkkgk.kwAk.
.kAAAQkkgkkwAAAk
.kAAAQkkgkkAAAQk
.kAAQQkkgkkAAQQk
..kQQk.kgk.kQQk.
...kk..kgk..kk..
.....kkggdkk....
...eexxmxxxee...
`,
melon: `
................
................
..........kkk...
.........kgllk..
......kxkkggdk..
....kkkxkkkk....
...kAfAAfAAQk...
..kAwAfAAfAQQk..
.kAwfAAfAAfAQQk.
.kAfAAfAAfAAQQk.
.kfAAfAAfAAfQQk.
.kAAfAAfAAfQQQk.
..kfAAfAAfQQQk..
...kQQfQQQQQk...
....kkkkkkkk....
...eexxxxxxee...
`,
watermelon: `
................
................
..........kkk...
......kk.kgllk..
......kxkkggdk..
....kkkxkkkk....
..kkgdgddgdgkk..
.kgldggddggdgdk.
kglddggddggddgdk
kggddggddggddgdk
kggddggddggddgdk
kggddggddggddtdk
.kgddggddggdtdk.
..kkgdgddgddkk..
....kkkkkkkk....
...eexxxxxxee...
`,
squash: `
................
.......kk..kkk..
.kkk..kxmk.kgllk
kgllk.kkkk.kgldk
kglgdkkwAk.kggdk
kggddkkAAkkkgdk.
.kgdkkAAAQk.kk..
..kk.kAAAQk.....
....kAwAAAQk....
...kAwAAAAQQk...
...kAAAAAAQQk...
...kAAAAAQQQk...
...kQAAAQQQQk...
....kQQQQQQk....
.....kkkkkk.....
...eexxxxxxee...
`,
zucchini: `
..kkk...........
.kgllk.......kk.
kgllgdk.....kxmk
kglgddk.kkkkkxk.
.kgddk.klggddk..
..kkk.klggddk...
.....klgdgdk....
....klggddk.....
...klgdgdk......
..klggddk..kkk..
.kyggddk..kgllk.
kyoyddk..kgllgdk
.kyokkk..kggddk.
..kk.....kkgdkk.
..........kgk...
......eexmxxee..
`,
cucumber: `
..kkk.....kkk...
.kgllk...kglgk..
kgllggkkkgglgdk.
kglggdkgkggdddk.
.kgddkkgkkdddk..
..kkkkkgkkkkk...
..kgk.kgk.......
.kdgdkkgk..kgk..
.klgdkkgk.kdgdk.
.kwgdkkgk.klgdk.
.klgdkkgk.kwgdk.
.klwdkkgk.klwdk.
.klgdkkgk.kggdk.
.kggdkkgk..kdk..
..kdk.kgdk..k...
...eexxmxxxee...
`,
pumpkin: `
................
........kk......
.......kxmk..kk.
..kkkk.kxk..kglk
.kglgkkkxkkkkgdk
.kgkkyoooooookk.
..kyooyooroooork
.kyoyoooroooorrk
kyooyooorooorrrk
kyoyoooroooorrrk
kooyoooroooorrrk
kooooooroooorrrk
.krroooroooorrk.
..kkrrrrrrrrkk..
....kkkkkkkk....
...eexxxxxxee...
`,
corn: `
......k.k.k.....
......kmkyk.....
.......kmk......
......kgdk......
.kk...kgdk......
kglk..kgdk..km..
.kglk.kgdk.kmmk.
..kglkkgdkkyyyk.
...kglkgdkyoyok.
....kkkgdkoyoyk.
.....kkgdkyoyok.
....kkggdklyoyk.
...kglkgdkglyk..
..kglk.kgdkglk..
..kkk.kkgdkkk...
...eexxmxxxee...
`,
strawberry: `
................
..........kkk...
...kkk...kwwwk..
..kgllk..kwywk..
.kgllgdk.kkwkk..
.kgggddkkglgk...
..kgddkgllgdkkk.
...kkkkgggdkglgk
.kgdgdkkgk.kkk..
.kiryrkkgk......
.kryrrkkgkkgdgdk
.krrypkkgkkiryrk
..krpk.kgkkryrrk
...kk..kgkkrrypk
.....kkgdk.krpk.
...eexxmxxxe.kk.
`,
blueberry: `
................
.....kkkkkk.....
...kkgllgggkk...
..kglggggggddk..
.kglgkbckggdddk.
.kggkbccbkgkkdk.
kglgkbbnkgkbckdk
kgggdkkkggkbnkdk
kggkbckgggdkkddk
kgkbccbkggkbckdk
.kgkbnkgddkbnkk.
..kdkkddddkkdk..
...kkkkxxkkkk...
......kxxk......
.....kkxmkk.....
...eexxmxxxee...
`,
raspberry: `
................
..kkk.......kk..
.kglgk.....kglk.
.kggdk....kgdk..
..kkgk...kgkk...
....kgk.kgk.....
..kkkgkkgkkk....
.kiik.kggk.kiik.
kirrikkgdkkirrik
krirrkkgdkkrirrk
krrrpkkgdkkrrrpk
.krpk.kgdk.krpk.
..kk..kgdk..kk..
......kgdk......
.....kkgdkk.....
...eexxmxxxee...
`,
herb: `
................
................
....kk....kk....
...kglk..kglk...
..kglgdkkgdgk...
...kkgdkkgdk.kk.
.kk..kgkkgk.kglk
kglk.kgkkgkkgdk.
.kgdkkgkkgkgdk..
..kkgdkgkgkgk...
....kkgggggk....
......kgdgk.....
......kgdk......
......kgdk......
.....kkgdkk.....
...eexxmxxxee...
`,
basil: `
.......kk.......
......kwwk......
......kgwk......
....kk.kk.kk....
...kllk..kllk...
..kllgkggkglgk..
..kkggkgkkggkk..
.kkk.kkgkk.kkk..
kgllk.kgk.kllgk.
kllggkkgkkgglgdk
kgggdkkgkkggddk.
.kkddkkgkkddkk..
...kkkkgkkkk....
......kgk.......
.....kkgdkk.....
...eexxmxxxee...
`,
parsley: `
................
...kkk...kkk....
..kgdgk.kgdgk...
.kgdgdgkgdgdgkk.
kgdgdgdkdgdgdgdk
kdgdgdkgdgdgdgdk
kddgdkgdgdgkddgk
.kkdkkdgdgdkkdk.
...kgkkdddkkgk..
....kgkkdkkgk...
.....kgkgkgk....
......kgggk.....
......kgdk......
......kgdk......
.....kkgdkk.....
...eexxmxxxee...
`,
dill: `
..k.k.k..k.k.k..
.kykykyk.kykyky.
..kkykk...kkyk..
....kk.....kk...
....kgk...kgk...
.k.k.kgk.kgk....
kgkgk.kgkgk..k.k
.kgk.k.kgk..kgkg
..kgkgk.kgk.kgk.
.k.kgk..kgkgk.k.
kgk.kgk.kgkgkgk.
.kgkkgk.kgkk.kgk
..kgkkgkkgk.kgk.
....kkgdkgkkk...
.....kkgdkk.....
...eexxmxxxee...
`,
rosemary: `
................
....k..k..k.....
...kck.kck.kck..
...ktk.ktk.ktk..
..kttkkttkkttk..
..ktdkktdkktdk..
.kttkkttdkkttk..
.ktdkkttkkttdk..
.kttkktdkkttk...
..ktdktdkkttk...
..kttkttkktdk...
...kxkxxkkxk....
....kxkxkxk.....
.....kxxxk......
.....kkxxkk.....
...eexxmxxxee...
`,
flower: `
................
.....kkkkk......
....kAAkAAk.....
...kAwAkAAQk....
...kAAkBBkQk....
..kkkkBwBVkkk...
..kAAkBBVkAQk...
..kAwAkVVkAQk...
...kAAQkkAQk....
....kkkgkkk.....
...kk..kgk......
..kglk.kgk.kk...
..kggdkkgkkglk..
...kkdkkgkkgdk..
.....kkkgdkk....
...eexxmxxxee...
`,
dahlia: `
................
.....kkkkkk.....
...kkAwAAAQkk...
..kAwAkAAkAQQk..
..kwAkAwAAkAQk..
.kAAkAkAAQkAQQk.
.kAkAAkyyykAAQk.
.kAkAwkyoykQAQk.
.kAAkAAkkkQAQQk.
..kAQkAAQQkQQk..
..kkQQkQQkQQkk..
....kkkkkkkk....
...kk..kgk.kkk..
..kglkkkgkkggdk.
...kkkkkgdkkkk..
...eexxmxxxee...
`,
marigold: `
................
................
...kkkk...kkk...
..kyoyok.kyoyk..
.kyoyyork.yoyrk.
.kooyoork.kooork
.kroooork.kroork
..krrrrk..krrrk.
..kkkkkkkkkkkk..
.kgldkkgk.kkgdk.
kgllgdkgkkgllgdk
kggddkkgkkgggddk
.kgdkkkgkkkgddk.
..kkkkkgdkkkkk..
.....kkgdkk.....
...eexxmxxxee...
`,
nasturtium: `
................
......kkk.......
.....kooyk......
....koyoork.kkk.
....kooork.kglk.
..kkkkrrk.kglggk
.kglgk.kk.kgggdk
kglllgkgk..kgdk.
kgllggkgk...kk..
kgggddkgkkkk....
.kgddk.kgkgllk..
..kkkkkgkgllggk.
...kook.kglggdk.
..kooyokkkgddk..
...kork.kkkkk...
...eexxmxxxee...
`,
sunflower: `
....kk.kk.kk....
...kyykyykyyk...
..kyyyyyyyyyyk..
.kyyyeeeeeeyyok.
kyyyexmxxxxeyook
.kyexmxxexxxeok.
.kyexxxexexxeok.
kyyyexxexeexeook
.kyyoeeeeeeoook.
..kyyooyyoooyk..
...kyokyokyok...
....kk.kgk.kk...
..kkk..kgk.kkk..
.kglgk.kgkkglgk.
..kkgdkkgkkgkk..
...eexxmxxxee...
`,
lupine: `
.......kk.......
......kAAk......
......kwAk......
.....kAAQAk.....
.....kwAkAk.....
.....kAAQAk.....
....kAwAkAQk....
....kAAQAAQk....
....kwAkAQQk....
....kAAQAAQk....
.....kkkgkk.....
.kk.k.kgk.k.kk..
kgdkgkkgkkgkgdk.
.kggggkgkggggk..
..kkkkkgdkkkk...
...eexxmxxxee...
`,
bulb: `
................
......kkk.......
.....kAAAk......
..kkkAwAAkkk....
.kAAkkQkQkAAk...
.kAwAkAAAkAQk...
..kAAkAAAkQk....
...kkkkQkkk.....
.....kQAQk......
......kkk.......
...k...kg....k..
..kgk..kgk..kgk.
..kgk..kgk.kgdk.
...kgk.kgk.kdk..
....kgkkgdkdk...
...eexxmxxxee...
`,
euphorbia: `
................
...kkk....kkk...
..kAwAk..kAAQk..
..kAAQkkkAAQQk..
...kkkAAAQkkk...
....ktkAQkktk...
..kttkktkktdk...
.kktdktktktdkk..
kttkktdtdtkkttk.
.kkttkdtdkttdk..
..ktdttdtdttdk..
...kkttdtdtkk...
....kktdtdkk....
......kttk......
.....kkdtkk.....
...eexxmxxxee...
`,
tree: `
.....kkkkkk.....
...kkgllgggkk...
..kglggAkgggdk..
.kglgAwAQgddgdk.
.kgggkAQkgdAkdk.
.kgAkggggdAwAdk.
.kAwAgdgdgkAQdk.
.kkAQkggddgdddk.
..kdgdddkdddkk..
...kkkkxmxkkk...
......kxmk......
...kkkkxmkkkkk..
...kyooooooork..
....koyooorrk...
....kooooorrk...
.....kkkkkkk....
`,
fig: `
...kk..kk..kk...
..kglkkglkkgdk..
.kgllgkgllgkgdk.
kgllggdglggdgddk
kglgggdgggddgddk
.kggdgkgdgdkddk.
..kk.kkshkk..kk.
.kuk..kshk..kuk.
kiupk.kshk.kiupk
kuppk.kshk.kuppk
.kkk..kshk..kkk.
......kshk......
......kshk......
......kshk......
.....kkshkk.....
...eexxmxxxee...
`,
groundcherry: `
................
...kkk....kkk...
..kgllk..kglgk..
.kgllggkkgggddk.
.kggdkgkkgkkddk.
..kkk.kgkgk.kk..
.....kmkgkm.....
....kyykgkymk...
...kyyymkymmmk..
...kfyymkymmmk..
...kymmmkkmmxk..
....kmmkgk.kk...
.....kkkgk......
.......kgk......
.....kkkgdkk....
...eexxmxxxee...
`,
tomatillo: `
................
...kkk....kkk...
..kgllk..kglgk..
.kgllggkkgggddk.
.kggdkgkkgkkddk.
..kkkkgkkgkkkk..
.....klkkkl.....
...kklllkllgkk..
..klllggkkgglgk.
..klwllgkklgggdk
..kllggdkkggggdk
..kglgdgkkgggddk
...kggddkkkgddk.
....kkkkgkkkkk..
.....kkkgdkk....
...eexxmxxxee...
`,
shrub: `
................
................
......kkkkk.....
....kkgllgdkk...
...kglllgggddk..
..kglllggggdddk.
..kgllgggggdddk.
.kglgggggddgddk.
.kggggdgggdddddk
.kgggdggggddddnk
.kdgggggdgdddnk.
..kddgddddddnk..
...kkdddddnkk...
.....kkkxkkk....
......kkxk......
...eexxmxxxee...
`,
unknown: `
................
..kkkkkkkkkkkk..
..kffmfmffmffk..
..kmmmmmmmmmmk..
..kffffffffffk..
..kffkkkkfffhk..
..kfkkffkkffhk..
..kfffffkkffhk..
..kffffkkfffhk..
..kfffkkffffhk..
..kffffffffffk..
..kfffkkffffhk..
..kfffkkfffhhk..
..khhhhhhhhhhk..
..kkkkkkkkkkkk..
................
`,

// ================================================================= icons ==
icon_yard: `
.kkkkkkkkkkkkkk.
kglggggffggggggk
kgmmmmgffgmmmmgk
kgmelmgffgmlemgk
kgmlemgffgmelmgk
kgmelmgffgmlemgk
kgmmmmgffgmmmmgk
kgggggffffggglgk
kggggggffggggggk
kgmmmmgffgmmmmgk
kgmlemgffgmelmgk
kgmelmgffgmlemgk
kgmlemgffgmelmgk
kgmmmmgffgmmmmgk
kgggglgffggggdgk
.kkkkkkkkkkkkkk.
`,
icon_bed: `
................
................
................
....k.k..k.k....
...kgklk.kglk...
....kgk...kgk...
.kkkkkkkkkkkkkk.
kmyyyyyyyyyyyymk
kxmmmmmmmmmmmmxk
kxkeexeexeexekxk
kxmmmmmmmmmmmmxk
kxxxxxxxxxxxxxxk
kxmmmmmmmmmmmmxk
kxxxxxxxxxxxxxxk
kkkkkkkkkkkkkkkk
................
`,
icon_calendar: `
................
...kk.....kk....
.kkhskkkkkhskkk.
kryrrrrrrrrrrrrk
krrrrrrrrrrrrrrk
kkkkkkkkkkkkkkkk
kwwwwwwwwwwwwwsk
kwkkwkkwkkwkkwsk
kwkkwkkwkkwkkwsk
kwwwwwwwwwwwwwsk
kwkkwkkwrrwkkwsk
kwkkwkkwrrwkkwsk
kwwwwwwwwwwwwwsk
kssssssssssssssk
kkkkkkkkkkkkkkkk
................
`,
icon_book: `
................
..kkkkkkkkkkkk..
.kgglggggggggdk.
.kglkkkkkkkgddk.
.kggkllkllkgddk.
.kggkllkllkgddk.
.kggkkkgkkkgddk.
.kgggggkgggggdk.
.kgggggkgggggdk.
.kgggggggggggdk.
.kgggggggggggdk.
.kdddddddddddkk.
.kwwwwwwwwwwwsk.
.kfffffffffffsk.
..kkkkkkkkkkkk..
................
`,
icon_basket: `
................
.....kkkkkk.....
....kmkkkkmk....
...kmk....kmk...
...kmkkkkkkmk...
..kkrrkgkkoookk.
.kryrrkglkooyok.
.krrrpkgdkoooork
kkkkkkkkkkkkkkkk
kmymmymmymmymmmk
kxmxxmxxmxxmxxxk
kmmymmymmymmymmk
.kxmxxmxxmxxmxk.
.kmmymmymmymmmk.
..kkkkkkkkkkkk..
................
`,
icon_seed: `
................
..kkkkkkkkkkkk..
..kffmffmffmfk..
..kmmmmmmmmmmk..
..kffffffffffk..
..kfkkkkkkkkfk..
..kfkcckkcckfk..
..kfkckglkckfk..
..kfkcckgcckfk..
..kfkxxkgxxkfk..
..kfkkkkkkkkfk..
..kffffffffffk..
..kfkkkkkkfffk..
..kffffffffffk..
..kkkkkkkkkkkk..
................
`,
icon_can: `
................
.....kkkk.......
....k....k......
....k....k......
..kkkkkkkkk..kkk
.kccwccccsck.kck
.kcwccccccck.kck
.kccccccccckksk.
.kcccccccccksk.c
.kcccccccccsk...
.kbcccccccbk..c.
.kbbbbbbbbbk....
.knbbbbbbbnk....
..kkkkkkkkk.....
................
................
`,
icon_frost: `
................
.......kk.......
.....kkcck......
....kcwcwk......
..kk.kwwk..kk...
.kckk.kwk.kkck..
..kwwkkwkkwwk...
kkkkwwwwwwwkkkk.
kccwwwwswwwwcck.
kkkkwwwwwwwkkkk.
..kwwkkwkkwwk...
.kckk.kwk.kkck..
..kk.kwwk..kk...
....kcwcwk......
.....kkcck......
.......kk.......
`,
icon_sun: `
................
.......kk.......
..k....ky....k..
.kyk...ky...kyk.
..kyk.kkkk.kyk..
....kkyyyykk....
...kyywyyyook...
kkkkyywyyyyokkkk
kyyyyyyyyyyoyyyk
.kkkyyyyyyookkk.
....kyyyyooo....
....kkooookk....
..kyk.kkkk.kyk..
.kyk...ky...kyk.
..k....ky....k..
.......kk.......
`,
icon_shovel: `
................
...........kkk..
..........kmyk..
..........kkmk..
.........kmkk...
........kmk.....
.......kmk......
......kmk.......
..kkkkkxk.......
.kswwskk........
kswwsshk........
kswsshhk........
kssshhk.........
kshhhk..........
kkkkk...........
................
`,
icon_gear: `
................
.....kk..kk.....
....kwwkkwsk....
....kwwwwssk....
..kkwwwwsssskk..
.kwwwwwsssssssk.
.kwwwwskksssshk.
..kwwsk..ksshk..
..kwssk..kshhk..
.kwsssskkshhhhk.
.kssssssshhhhhk.
..kksssshhhhkk..
....ksshhhhk....
....kshkkhhk....
.....kk..kk.....
................
`,
icon_plus: `
................
................
......kkkk......
......klgk......
......klgk......
......klgk......
..kkkkklgkkkkk..
..kllllllgggdk..
..kgggggggggdk..
..kkkkkggdkkkk..
......kggk......
......kgdk......
......kgdk......
......kkkk......
................
................
`,
icon_trash: `
................
......kkkk......
.....kk..kk.....
..kkkkkkkkkkkk..
.kwssssssssshhk.
.kkkkkkkkkkkkkk.
..kswsswsswshk..
..kswhswhswhhk..
..kswhswhswhhk..
..kswhswhswhhk..
..kswhswhswhhk..
..kswhswhswhhk..
..kssssssssshk..
...khhhhhhhhk...
...kkkkkkkkkk...
................
`,
icon_lock: `
................
.....kkkkkk.....
....kssssssk....
...kswkkkkshk...
...ksk....khk...
...ksk....khk...
..kkkkkkkkkkkk..
..kyywyyyyyyok..
..kywyyyyyyook..
..kyyyykkyyyok..
..kyyyykkyyook..
..kyyyyykyyook..
..kyyyyyyyyook..
..kooooooooork..
..kkkkkkkkkkkk..
................
`,
icon_unlock: `
..........kkkk..
.........kssssk.
........kswkkshk
........ksk..khk
........ksk..kkk
........ksk.....
..kkkkkkkkkkkk..
..kyywyyyyyyok..
..kywyyyyyyook..
..kyyyykkyyyok..
..kyyyykkyyook..
..kyyyyykyyook..
..kyyyyyyyyook..
..kooooooooork..
..kkkkkkkkkkkk..
................
`,
icon_user: `
................
.....kkkkkk.....
....kxxxxxxk....
...kxmmxxxxxk...
...kxffffffxk...
...kfwfffffok...
...kfffffffok...
....kffffook....
.....kkkkkk.....
...kkttttttkk...
..kttgtttttttk..
.kttgtttttttdtk.
.ktgtttttttddtk.
.kttttttttddddk.
.kkkkkkkkkkkkkk.
................
`,
icon_cloud: `
................
................
................
......kkkk......
.....kwwwwk.....
..kkkwwwwwwkk...
.kwwwwwwwwwwwk..
kwwwwwwwwwwgwsk.
kwwwwwwwwwgdwsk.
kwwwwgwwwgdwssk.
kswwwdgwgdwsssk.
.kssswwgdssssk..
..kkkkkkkkkkk...
................
................
................
`,
icon_cloud_off: `
................
.kk.............
kkrk...kkkk.....
.krrk.kssssk....
..krrkssssshkk..
..kkrrkssssshhk.
.kssskrrkssshhhk
.ksssssrrksshhhk
ksssssskrrkshhhk
kssssssskrrkhhhk
khssssssskrrkhhk
.khhhhhhhhkrrkk.
..kkkkkkkkkkrrk.
............krk.
.............kk.
................
`,
icon_sprout: `
.kkk........kkk.
kwllkk....kkllgk
klllllk..kllggdk
kllllggkkgglgddk
.kllgggkkggdddk.
..kkggdkkgddkk..
....kkkgdkkk....
.kkkkkkgdkkkkkk.
kyyyyyyyyyyyyyok
kyoooooooooooork
.kkkkkkkkkkkkkk.
..koyooooooorrk.
..koyoooooorrrk.
...koyooooorrk..
...kooooooorrk..
....kkkkkkkkk...
`,
icon_map: `
................
................
.kkkkkkkkkkkkkk.
.kfflfmyyymfffk.
.kfllfmyycmrfrk.
.kfgffmycymfrfk.
.kfffcmcyymrfrk.
.kffccmyyymrffk.
.kfcffmyyrmfffk.
.kcfffmryymfgfk.
.kcffrmyyymggfk.
.kfrffmylymfgfk.
.kffffmyyymfffk.
.kkkkkkkkkkkkkk.
................
................
`,
icon_check: `
................
................
.............kk.
............kglk
...........kglk.
..........kglk..
.kk......kglk...
kglk....kglk....
.kglk..kglk.....
..kglkkglk......
...kglglk.......
....kglk........
.....kk.........
................
................
................
`,
icon_close: `
................
................
..kk........kk..
.kiok......kiok.
..korok..korok..
...korokkorok...
....korrorok....
.....korrok.....
.....korrok.....
....korrorok....
...korokkorok...
..korok..korok..
.krok......krok.
..kk........kk..
................
................
`,
icon_edit: `
................
............kk..
...........kiik.
..........kiirk.
.........kkkrk..
........kyykk...
.......kyyok....
......kyyok.....
.....kyyok......
....kyyok.......
...kyyok........
...kfok.........
..kffk..........
..kkk...........
................
................
`,
icon_warn: `
................
.......kk.......
......kyyk......
......kyyk......
.....kyyyyk.....
.....kykkyk.....
....kyykkyyk....
....kyykkyyk....
...kyyykkyyyk...
...kyyykkyyyk...
..kyyyyyyyyyok..
..kyyyykkyyyok..
.kyyyyykkyyyook.
.kooooooooooook.
.kkkkkkkkkkkkkk.
................
`,
icon_heart: `
................
................
..kkkk....kkkk..
.kiiirk..krrrrk.
kiwirrrkkrrrrrpk
kiirrrrrrrrrrrpk
kirrrrrrrrrrrppk
krrrrrrrrrrrrppk
.krrrrrrrrrrppk.
..krrrrrrrrppk..
...krrrrrrppk...
....krrrrppk....
.....krrppk.....
......kppk......
.......kk.......
................
`,
icon_clash: `
................
.........kkkk...
........kyyok...
.......kyyok....
......kyyok.....
.....kyyok......
....kyyokkkkk...
...kyyyyyyyok...
...kkkkkyyok....
.......kyok.....
......kyok......
.....kyok.......
....kyok........
...kyok.........
...kkk..........
................
`,

// ================================================================= tiles ==
tile_grass: `
gggggggggggggggg
gggglggggggggggg
ggggldgggggggdgg
gggggggggggggldg
gggggggggggggggg
gggggggdgggggggg
glggggglgggggggg
gldgggggggggglgg
ggggggggggggggdg
gggggggggggggggg
ggggggglgggggggg
gggdgggldggggggg
gggldggggggggdgg
gggggggggggggldg
gggggggggggggggg
gggggggggdgggggg
`,
tile_grass2: `
gggggggggggggggg
gggglggggggggggg
ggggldgggggwgggg
gggggggggggwyggg
gggggggggggggggg
gggggggdgggggggg
glggggglgggggggg
gldgggggggggglgg
ggggggggggggggdg
ggggiggggggggggg
gggiyigglggggggg
gggdigglddgggggg
gggldggggggggdgg
gggggggggggyglgg
ggggggggggyoyggg
gggggggggdgygggg
`,
tile_soil: `
xxxxxxxxxxxxxxxx
xxmxxxxxxxxxexxx
xxxxxxxexxxxxxxx
xxxxxxxxxxxxxxxx
xexxxxxxxxmxxxxx
xxxxxmxxxxxxxxxx
xxxxxxxxxxxxxxex
xxxxxxxxexxxxxxx
xxmxxxxxxxxxxxxx
xxxxxxxxxxxmxxxx
xxxxexxxxxxxxxxx
xxxxxxxxxxxxxxxx
xxxxxxxmxxxxexxx
xexxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxmx
`,
tile_soil2: `
xmxxmxxxxmxxmxxx
xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx
eeeeeeeeeeeeeeee
eeeexeeeeeeexeee
mxxmxxxmxxxxmxxm
xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx
eeeeeeeeeeeeeeee
eexeeeeeexeeeeee
xmxxxmxxmxxxxmxx
xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxx
eeeeeeeeeeeeeeee
eeeeeeexeeeeeeee
xxxxxxxxxxxxxxxx
`,
tile_path: `
xwwwwwxxxwwwwwxx
wssssshxwssssshx
wssssshxwshssshx
wsshsshxxhhhhhxx
wsssshhxxxxxxxxx
wssssshxxwwwwwxx
xhhhhhxxxhhhhhxx
xxxexxxexxxxxxxx
wwxxxwwwwwxxxwww
sshxwssssshxwshs
hhxxwssssshxxhhh
xxxxwsshsshxxxxx
wwxxwssssshxxwww
shhxwssssshxwsss
hhxxxhhhhhxxxhhh
xxxxxxxxxxxxxxxe
`,
tile_wood: `
yymmmmmmmmmmmmmm
mmmmmmxmmmmmmmmm
mmxxmmmmmmmmxxmm
xxxxxxxxxxxxxxxx
mmmmmmmmmmmkymmm
mmmmxmmmmmmkmmmm
mmmmmmmmxxmkmmmm
xxxxxxxxxxxxxxxx
ymmmmmmmmmmmmmmm
mmmmmmmmmmxmmmmm
mxxmmmmmmmmmmmxm
xxxxxxxxxxxxxxxx
mmmmkymmmmmmmmmm
mmmmkmmmmxxmmmmm
mxmmkmmmmmmmmmmm
xxxxxxxxxxxxxxxx
`,
tile_water: `
bbbbbbbbbbbbbbbb
bbbcccbbbbbbbbbb
bbcbbbcbbbbbbbbb
bbbbbbbbbbbbbbbb
bbbbbbbbbbbwcbbb
bbbbbbbbbbcbbcbb
bbbbbbbbbbbbbbbb
bnbbbbbbbbbbbbbb
bbbbbbbbbbbbbbbb
bbbbbbcccbbbbbbb
bbbbbcbbbcbbbbbb
bbbbbbbbbbbbbbnb
bbbbbbbbbbbbbbbb
cbbbbbbbbbbbbbbc
bcbbbbbbbbbbbbcb
bbbbbbbbbbbbbbbb
`,
};

/* -------------------------------------------------------------- build -- */

function parseArt(src) {
  return src.split('\n').map((r) => r.trim()).filter((r) => r.length > 0);
}

export const SPRITES = Object.freeze(
  Object.fromEntries(
    Object.entries(ART).map(([key, src]) => [key, Object.freeze({ rows: Object.freeze(parseArt(src)) })]),
  ),
);

export const SPRITE_KEYS = Object.freeze(Object.keys(SPRITES));

export function hasSprite(key) {
  return typeof key === 'string' && Object.prototype.hasOwnProperty.call(SPRITES, key);
}

function resolveKey(key) {
  return hasSprite(key) ? key : 'unknown';
}

/* ------------------------------------------------------------- colour -- */

function parseHex(hex) {
  if (typeof hex !== 'string') return null;
  let h = hex.trim().replace(/^#/, '');
  if (/^[0-9a-f]{3}$/i.test(h)) h = h.split('').map((c) => c + c).join('');
  if (!/^[0-9a-f]{6}$/i.test(h)) return null;
  const n = parseInt(h, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function shade(rgb, amt = SHADE_AMOUNT) {
  return rgb.map((v, i) => Math.round(v + (INK[i] - v) * amt));
}

// char -> [r,g,b,a] for one sprite + tint
function colourMap(key, tint) {
  const t = tint && typeof tint === 'object' ? tint : {};
  const def = DEFAULT_TINTS[key] || {};
  const A = parseHex(t.A) || parseHex(def.A) || parseHex(FALLBACK_TINT.A);
  const B = parseHex(t.B) || parseHex(def.B) || parseHex(FALLBACK_TINT.B);
  const Q = parseHex(t.Q) || shade(A);
  const V = parseHex(t.V) || shade(B);
  const map = { A: [...A, 255], Q: [...Q, 255], B: [...B, 255], V: [...V, 255] };
  for (const [ch, hex] of Object.entries(PALETTE)) {
    const rgb = parseHex(hex);
    map[ch] = rgb ? [...rgb, 255] : [0, 0, 0, 0];
  }
  return map;
}

/* ------------------------------------------------------------- render -- */

// PURE: RGBA pixels for a sprite. Unknown keys render the `unknown` sprite.
export function renderToRGBA(key, tint = {}) {
  const k = resolveKey(key);
  const rows = SPRITES[k].rows;
  const cmap = colourMap(k, tint);
  const w = 16, h = 16;
  const data = new Uint8ClampedArray(w * h * 4);
  for (let y = 0; y < h; y++) {
    const row = rows[y] || '';
    for (let x = 0; x < w; x++) {
      const c = cmap[row[x]] || [0, 0, 0, 0];
      const o = (y * w + x) * 4;
      data[o] = c[0]; data[o + 1] = c[1]; data[o + 2] = c[2]; data[o + 3] = c[3];
    }
  }
  return { w, h, data };
}

function tintId(key, tint) {
  const k = resolveKey(key);
  const t = tint && typeof tint === 'object' ? tint : {};
  const norm = {};
  for (const s of TINT_SLOTS) if (t[s] != null) norm[s] = String(t[s]).toLowerCase();
  return k + '|' + JSON.stringify(norm);
}

// DOM: a canvas with the sprite drawn at `scale` (integer, nearest-neighbour).
export function spriteCanvas(key, tint = {}, scale = 1) {
  const { w, h, data } = renderToRGBA(key, tint);
  const s = Math.max(1, Math.round(Number(scale) || 1));
  const base = document.createElement('canvas');
  base.width = w; base.height = h;
  const bctx = base.getContext('2d');
  bctx.putImageData(new ImageData(data, w, h), 0, 0);
  if (s === 1) return base;
  const out = document.createElement('canvas');
  out.width = w * s; out.height = h * s;
  const ctx = out.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(base, 0, 0, w * s, h * s);
  return out;
}

const urlCache = new Map();

// DOM: PNG data URL at native 16x16, memoised per key + tint.
export function spriteURL(key, tint = {}) {
  const id = tintId(key, tint);
  let url = urlCache.get(id);
  if (!url) {
    url = spriteCanvas(key, tint, 1).toDataURL('image/png');
    urlCache.set(id, url);
  }
  return url;
}
